version: "3.8"

services:
  # -----------------------------
  # FastAPI Application
  # -----------------------------
  app:
    build: .
    image: goodbooksunisoft/goodbooks-chatbot:latest
    container_name: goodbooks_chatbot_app
    ports:
      - "8010:8010"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
